config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  get 'login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'new_session'


  delete '/logout', to: 'sessions#logout', as: 'logout'
  

  resources :users
  resources :interests
  resources :locations
  resources :events
  resources :registrations

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :registrations 
    has_many :users, through: :registrations 
    belongs_to :user 
    belongs_to :location
    belongs_to :interest 


    validates :name, presence: true, uniqueness: { scope: :location_id,
    message: 'Event with the same name already exists'}
    validates :location_id, presence: true
    validates :interest_id, presence: true
    
    def self.search(search)
        if search 
            location = Location.find_by(city: search)
            if location 
                self.where(location_id: location)
            else
                @events = Event.all 
            end
        else
            @events = Event.all 
        end
    end

    
end

app/models/interest.rb
class Interest < ApplicationRecord
    has_many :events
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :events
end

app/models/registration.rb
class Registration < ApplicationRecord
    belongs_to :user 
    belongs_to :event 

    validates :user_id, presence: true
    validates :event_id, presence: true
 
    validates  :user_id, uniqueness: { scope: :event_id,
    message: 'You have already registered for this Event'}


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :registrations 
    has_many :events, through: :registrations 

    validates :name, presence: true 
    validates :email, presence: true, uniqueness: {message: ' : User with the same email address already exists!'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized

    # private 

    def current_user
        @current_user = User.find_by(id: session[:user_id])
        # helper_method :current_user #make private method accessible for the view
    end
    
    def logged_in
        !!current_user
    end

    def authorized
        redirect_to login_path unless current_user
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    skip_before_action :authorized, only: [:index] 
 
    def index 
    # if current_user
    @events = Event.search(params[:search])
     end
    # end

    
    
    


    def show
    @event = Event.find(params[:id])
    @registrations = @event.registrations.each do |reg| reg.user.name
    end
    end

    def new 
        @event = Event.new
    end

    def create 

        @event = Event.create(event_params)
        if @event.valid?
        
        redirect_to event_path(@event) 

        else 
        @errors = @event.errors.full_messages
        render :new
        end
    end

    def edit 
        @event = Event.find(params[:id])
    end 

    def update 
        @event = Event.find(params[:id])
        @event.update(event_params)
        if @event.valid?
            redirect_to event_path(@event) 
        else 
            @errors = @event.errors.full_messages
            render :edit
        end 
    end

    def destroy
         @event = Event.find(params[:id])
         @event.destroy 
        redirect_to user_path(@event.user_id)
    end

    

   private 

   def event_params
   params.require(:event).permit(:name, :date, :location_id, :description, :user_id, :interest_id, :img_url, :search)
   end

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
    def index 
        @interests=Interest.all
    end

    def show 
        @interest=Interest.find(params[:id])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index 
        @locations = Location.all
    end 

    def show 
        @location = Location.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    

    def new
        @registration = Registration.new
    end

    def create 
        #@event= event.each {|event| event}
        @registration=Registration.create(registration_params)
        @current_user.registrations << Registration.create(registration_params)
        redirect_to user_path(@current_user.id)
   

    end

    def destroy 
        @registration = Registration.find(params[:id])
        @registration.destroy 
        redirect_to user_path(@registration.user_id)
    end

    private 
    def registration_params
    params.require(:registration).permit(:user_id, :event_id) 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authorized, only: [:new, :create]

    def new
    end

    def create #login - looks up user in db, verify login, store auth. user's id in the session
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password]) #find user or authenticate by grabbing pw_digest from user
            session[:user_id] = @user.id 
        
            redirect_to user_path(@user)
        else
            flash[:errors] = "Username or password is incorrect"
            redirect_to new_session_path
        end
    end

    def logout
        session.delete(@current_user.id)
        @current_user = nil 
    
        redirect_to new_session_path

    end

    def reset_page
        cookies[:page_count] = 0
        
        redirect_back fallback_location: events_path
      end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def index
        @users = User.all
    end

    def new
        @user = User.new 
        @errors = flash[:my_errors] 
    end

    def show 
        @events = Event.all
        @created_events = @events.select { |event|  event.user_id == current_user.id } 

        if current_user
        render :show 
        else 
        flash[:my_errors] = "Please log in to view your profile."
        redirect_to login_path
        end

    end

    def create
        user = User.create(strong_params)
        if user.valid?
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:errors] = user.errors.full_messages 
            redirect_to new_user_path      
        end
    end

    private

    def strong_params
        params.require(:user).permit(:name, :email, :img_url, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit Your Event: </h1>
<% if @errors %>
    <% @errors.each do |error| %> 
        <%= error %> <br>
        <% end %>
        <% end %> 
        <br>
        <br>

        <%= form_for @event do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name%>  
        <%= f.label "Date and time (format: mm-dd-yyyy, hh:mm)" %> 
        <%= f.text_field :date %> 
        <%= f.label :location %>
        <%= f.collection_select :location_id, Location.all, :id, :city %> 
        <%= f.label :description %>
        <%= f.text_field :description %> 
        <%= f.label :interest %>
        <%= f.collection_select :interest_id, Interest.all, :id, :name %> 
        <%= f.label :img_url %>
        <%= f.text_field :img_url %>  <br>
        <%= f.submit "SUBMIT" %>
        <% end %>
        <br>

       

app/views/events/index.html.erb
<h3>Discover events for all the things you love...</h3>
<%= form_tag(events_path, method: :get) do %>
<%= text_field_tag(:search, params[:search]) %>
<%= submit_tag ("Search by City") %>
<% end %>

<!-- END OF SEARCH BAR -->
 

<div class="grid-container">
<%@events.each do |event|%>

<div class="grid-item">
<div class="font" %><%= link_to event.name, event_path(event) %></div>
<img  class="img" src="<%= event.img_url %>" alt="<% event.name %>" >
</div>
<% end %>
</div>

app/views/events/new.html.erb


<% if @errors %>
    <% @errors.each do |error| %> 
        <%= error %> <br>
        <% end %>
        <% end %> 

        <br>
        <br>
   
        <%= form_for @event do |f| %>
         <%= f.label :name , "Event Name"%>
        <%= f.text_field :name%>  
        <%= f.label "Date and time (format: mm-dd-yyyy, hh:mm)" %> 
        <%= f.text_field :date %> 
        <%= f.label :location %>
        <%= f.collection_select :location_id, Location.all, :id, :city %> 
        <%= f.label :description %>
        <%= f.text_field :description %> 
        <%= f.label :interest %>
        <%= f.collection_select :interest_id, Interest.all, :id, :name %> 
        <%= f.label :img_url %>
        <%= f.text_field :img_url %>  <br> 
        <%= f.label :user %>
        <%= f.collection_select :user_id, User.all.select {|cu| cu.id == @current_user.id}, :id, :name %>
        <%=f.submit "Create Event"%>
        <% end %>
        <br> <br> <br><br> <br> <br> 


        <!-- LINES DELETED
        f.label :user
        f.collection_select :user_id, User.all, :id, :name
    

app/views/events/show.html.erb
<h1> <%= @event.name %></h1>


<h2> Date: <%= @event.date.strftime("%A, %B %d, %Y") %></h2>
<h2>Location: <%= link_to @event.location.city, location_path(@event.location) %></h2>

<div class="event-description">
<p><h2>Event Details: <%= @event.description %></h2></p>
<img class="event-pic" src="<%= @event.img_url %>" alt="<% @event.name %>" >
</div>

<form  method="get" action="/registrations/new" >
 <input value="Register" type="submit" />
</form> 

<h2>Attendees:</h2>
<ol><% @registrations.each do |reg| %>

<li><h3><%= reg.user.name %></h3></li>
<% end%></ol>
<h3> Event created by: <%= @event.user.name%>
<img class="avatar" src="<%= @event.user.img_url %>" alt="<% @event.user %>"  > </h3>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/interests/index.html.erb
<h1> What are you interested in? </h1><br>

<% @interests.each do |interest| %>
    <h2><%= link_to interest.name, interest_path(interest) %> </h2>
    <% end %>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

app/views/interests/show.html.erb
<h2> All Events that match your interest: </h2>
<% @interest.events.each do |event| %>

    <h3> <%= link_to event.name, event_path(event) %> </h3> <br>
    <h4> Location: <%=event.location.city %> </h4>
     <h4> Date: <%= event.date.strftime("%A, %B %d, %Y") %></h4>
     <img src="<%= event.img_url %>" alt="<% event.name %>" style= "width:220px; height:160px; border:10;">

     <h4> Description: <%= event.description %></h4>
     <br>
     <br>
     <% end %>
     <br>
     <br>
     
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>So'Mate</title>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
  <div class="background"> </div>
  <ul  class="navigation"> 


      
      <li class="nav-bar"> <a href="/interests" > Look up by interest </a></li>
      <li class="nav-bar"> <a href="/locations" > All  locations </a></li>
      <li class="nav-bar"> <a href="/events" > Events </a></li> 
      <li class="nav-bar"> <a href="/events/new"> Create an Event</a> </li>

      <% if @current_user %>
      <li class="nav-bar"> <a href= "/users/@current_user.id"> My Events </a></li>

      <li class="nav-bar"><%= link_to 'Log Out', logout_path, method: 'delete' %></li>

     
      <li  id="welcome"> Welcome <%= @current_user.name %>!</li>

      <% else %>
      <li class="nav-bar"><%= link_to 'Sign up', new_user_path %></li>
      <li class="nav-bar"><%= link_to 'Login', new_session_path %></li>
      
      <% end %>









  </ul>
  <br>
  <br>
  
  
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
test

app/views/locations/index.html.erb
<h2> All locations: </h2>
<% @locations.each do |location| %>
    <h3><%= link_to location.city, location_path(location) %> <h3>
    <% end %>
    

app/views/locations/show.html.erb
<div class="city"><%= @location.city %> </div>

    <% @location.events.each do |event| %>
   
    <h2> <%= link_to event.name, event_path(event) %> </h2> <br>
    <img src="<%= event.img_url %>" alt="<% event.name %>" style= "width:220px; height:160px; border:10;">
     <h3> Date: <%= event.date.strftime("%A, %B %d, %Y") %> </h3>
     <h4> Description: <%= event.description %></h4>
     <br>
     <% end %>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>
     <br>

     



app/views/users/index.html.erb
<h1> All users: </h1><br>
<% @users.each do |user| %> <br>
    <%= link_to user.name, user_path(user) %> <br>
    <img src="<%= user.img_url %>" alt="<% user.name %>" style= "width:100px; height:100px; border:10;"> <br>
    <% end %>
    

app/views/users/new.html.erb
        
<h3>Please enter information below to start joining and creating events on So'Mate!</h3>
            
<%= form_for @user do |f| %>

<% if flash[:errors] %>
<% flash[:errors].map do |error|%>
<p style="color: red;"><%= error %></p>
<%end%>
<% end %>
                            
<label>Name:</label>
<%=f.text_field :name%> <br>
                               
<label>Email: </label>
<%=f.text_field :email %><br>
                               
<label >Password: </label>
<%=f.password_field :password %> <br>
                                
<label>Password Confirmation: </label>
<%= f.password_field :password_confirmation %> <br>
                               
<%= f.label "Profile Picture" %>
<%= f.text_field :img_url %>       
<br>
                               
<%= f.submit "Sign up" %> 

                              
<h2>If you already have an account:  <%= link_to "Log in!", login_path %></h2>
                      
<% end %>
                       

app/views/users/show.html.erb
<% if flash[:my_errors]%>
<p style="color: red;"><%= flash[:my_errors] %></p>
<% end %>

<h1><%= "#{@current_user.name}'s Events" %> </h1>
<img src="<%= @current_user.img_url %>" alt="" style= "width:60px; height:60px; ">
<h2> All events that you are registered for: </h2><br>
      <% @current_user.events.each do |event| %>
      <div>
      <h2><%= link_to event.name, event_path(event) %> </h2>
      <img src="<%= event.img_url %>" alt="<% event.name %>" style= "width:220px; height:160px; ">
     <p> <%= event.date.strftime("%A, %B %d, %Y") %></p>

     <% registration_for_deletion = event.registrations.select {|reg| reg.user_id == @current_user.id} %>
      <%= button_to 'Unregister', registration_path(registration_for_deletion), method: :delete %> 

      </div>
      <% end %>
      <br>

       <h2> All events that you created: </h2><br>
        <% @created_events.each do | event | %>
        <h2><%= link_to event.name, event_path(event) %> </h2>
        <img src="<%= event.img_url %>" alt="<% event.name %>" style= "width:220px; height:160px; ">
        <ul><%= link_to "Edit Event", edit_event_path(event) %></ul>
        <%= button_to 'Delete Event', event_path(event), method: :delete %>
        <%end%>

      
        
        
     
    
    
     